// <auto-generated />
namespace SeaSharpe_CVGS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Willthiswork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Willthiswork));
        
        string IMigrationMetadata.Id
        {
            get { return "201511111756139_Will this work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
